In [ ]:
# `01_numpy.ipynb`

# 이 부분은 MD 파일로 이동

In [3]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
python_list = [1,2,3,4,5]
# [2,4,6,8,10]

result = [x*2 for x in python_list]
print(result) 

[2, 4, 6, 8, 10]


In [5]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
result = array * 2
print(result)

[ 2  4  6  8 10]


In [11]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))
print('차원', arr.ndim)
print('형태', arr.shape)
print('크기',arr.size)

[1 2 3 4 5] <class 'numpy.ndarray'>
차원 1
형태 (5,)
크기 5


In [5]:
arr1d = np.array([1,2,3,4,5])
arr1d

array([1, 2, 3, 4, 5])

In [ ]:
l2d = [
    [1,2,3],
    [4,5,6]
]
arr2d = np.array(l2d)

arr2d.ndim, arr2d.shape, arr2d.size

arr2d 

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 실수형 arr
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [18]:
# 0으로 채워짐

z1d = np.zeros(5)
z2d = np.zeros((2,3))
print(z1d,z2d)

# 1로 채워짐

o1d = np.ones(5)
o2d = np.ones((2,3))

# n으로 채움-> 5칸, 7칸으로 체움
n1d = np.full(5,7)
n2d = np.full((2,3),7)

# 빈칸이지만 먼저 만듦
empty = np.empty(3)
print(empty)



[0. 0. 0. 0. 0.] [[0. 0. 0.]
 [0. 0. 0.]]
[1. 2. 3.]


In [ ]:
# 시퀀스 데이터
range_arr = np.arange(0,10,2)
print(range_arr) # 파이썬은 대문자, 소문자 오타 주의


np.array(range(0,10,2))

# 등간격 실수 배열
lin_space = np.linspace(0,1,5)
print(lin_space)

# 로그스케일
log_space = np.logspace(0,2,5) # 10^0 - 10^2 중 5개 요소
peint(log_space) 

[0 2 4 6 8]


array([0, 2, 4, 6, 8])

In [ ]:
# 난수 베열

# 균등 분포 # 0~1 실수 균등확률 분포
random = np.random.rand(3,3) # 0~1 실수
print(random)

# 정규 분포 난수
normal = np.random.randn(3,3)
print(normal)

# 정수 난수 
np.random.randint(0, 10, (3,3))
print(int_random)

# 시드 설정(랜덤 재현 가능) # 암호 관련 기술

np.random.seed(42) # 랜덤상황 42 고정
np.random.seed(3)

[[0.36290162 0.07992852 0.10131357]
 [0.24665478 0.53445454 0.12055611]
 [0.73982797 0.99413274 0.33207503]]


In [28]:
# 배열의 데이터 타입
# 데이터 타입 확인
arr = np.array([1,2,3])

# 데이터 타입 지정 생성
f_arr = np.array([1,2,3], dtype = np.float64)

# 데이터 타입 변경

converted = arr.astype(np.float64)
print(converted.dtype)

# 문자열 -> 숫자
str_arr = np.array(['1.2','2.3','3.4'])
num_arr = str_arr.astype(float) # np.floatXX 라고 지정 안 하고 float 쓰면 -> float64
print(str_arr, num_arr)


float64
['1.2' '2.3' '3.4'] [1.2 2.3 3.4]


In [ ]:
# memory 사용량
print(arr.itemsize) # 8byte
print(converted.itemsize) # 리ㅐㅁㅅ32 -> 4byte

# 총 메모리 사용량

print(arr.nbytes) # 8byte * 3칸 
print(converted.nbytes)

# 과학 기술 관련해서는 소수점도 중요하니깐 64byte, 하지만 Context에 따라서 

8
8
24
24


In [ ]:
# 배열 재구성
arr = np.arange(12)
print(arr) 

reshaped2d = arr.reshape(3,4)

print(reshaped2d) # 3row * 4col

reshaped3d = arr.reshape(2, 2, 3) # 2페이지, 2row * 3col
print(reshaped)

# 자동계산

auto1 = arr.reshape(3,-1)
auto2 = arr.reshape

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 1차원 => N차원
# reshape -> 원본 그대로, 새로운 배열 만드는
# resize -> 원본을 바꿈

arr = np.arrange(12)
reshaped = arr.reshape(3,4) # 새로운 배열 리턴
print(reshaped)
print(arr)

arr.resize(3,4) # arr이 바꿈


In [ ]:
# N차원 -> 1차원
arr = np.array([[1, 2, 3],[4, 5, 6]])

r = arr.ravel() # 뷰(원본 연결 및 참조) => 빨리 펼쳐서 보기
f = arr.flatten() # 복사본 => 안전하게 세로 만들기


r[0] = 100
f[0] = -100

print(arr)
print(r,f)

[[100   2   3]
 [  4   5   6]]
[100   2   3   4   5   6] [-100    2    3    4    5    6]


In [ ]:
# 전치 -> 행과 열을 교환
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d) # 배열 전치(Transpose): 행과 열을 뒤바꿔 2행 3열을 -> 3행 2열로 변경 (회전)

arr_2d.transpose(), arr_2d.T

[[1 2 3]
 [4 5 6]]


(array([[1, 4],
        [2, 5],
        [3, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [39]:
# 1~15 정수 베열

print(np.arange(1,16),np.array(range(1,16)))

# 0~9까지 홀수
print(np.arange(1,10,2))

# 0~1까지 균등하게 6등분 베열

print(np.linspace(0,3,6))

# 0~3까지 균등 6등분 (5구간) 배열
print(np.linspace(0,3,6))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 3 5 7 9]
[0.  0.6 1.2 1.8 2.4 3. ]
[0.  0.6 1.2 1.8 2.4 3. ]


In [ ]:
# 4*4 단위 행렬(identity metrix) -> 대각선 1, 나머지 0

print(np.eye(4))


# 3,4 사이즈의 1로 가득찬 int 배열

np.ones((3,4),dtype=int) 

# 2*3*4사이즈 0-1 난수 배열
np.random.rand(2,3,4) # 인자로 차원 지정 -> 오래된 버전에서 주로 씀
np.random.random((2,3,4)) # 튜플로 차원 지정 -> 최신 버전에서 주로 씀

print()
print()
print()

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [49]:
## 배열의 인덱싱/슬라이싱 

# 
# 
#  indexing 드디어 다른 세계의 인덱싱 가자!!

In [ ]:
# arr_2d = np.array(range(1,10)).reshape(3,3)

arr_2d = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

# numpy에서만 지원
arr_2d[0, 0]  # arr_2d[0][0] -> r 0, c 0
arr_2d[1, 1]

arr_2d[1] # 행 접근

# 변경

 arr_2ㅇ[0,0] =100
 arr_2d

 

5

In [ ]:
# 슬라이싱

arr = np.arange(10)
print(
    arr[2:5],
    arr[:5],
    arr[5:]
)

print(
    arr[1:8:2],
    arr[::2]
)

print(
    arr[::-1],
    arr[7:2:-1]
)

# 슬라이싱으로 일괄 변경(파이썬 고유 기능 X)
arr[3.6] = 100
print(arr)


[2 3 4] [0 1 2 3 4] [5 6 7 8 9]
[1 3 5 7] [0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0] [7 6 5 4 3]


In [ ]:
# 다차원 배열 슬라이싱
arr_2d = np.arange(1,13).reshape(3,-1)

print(arr_2d)

# row(행) 슬라이싱 -> 0,1 idx행
print(arr_2d[0:2])


# col(열) 슬라이싱 -> 모든 행의 idx 1,2열
print(arr_2d[:,0:2])

# row/col 동시 슬라이싱 -> 1,2행 / 0,1duf
print(arr_2d[1:3, 0:2])

# 간격지정 -> 행/열 모두 2간격
print(arr_2d[::2,::2 ]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 5  6]
 [ 9 10]]
[[ 1  3]
 [ 9 11]]


In [ ]:
# 다차원 배열 슬라이싱 변경
print(arr_2d)

## 부분 배녈 일괄 변경
arr_2d[0:2,0:2]
print(arr_2d)

## 브로드캐스팅


In [ ]:
# 다중 조건
print


In [ ]:
# 2차원 배열 불리언인덱싱

arr_2d = np.arange(1,10).reshape(3,3)

mask = arr_2d > 5 

print(arr_2d[mask]) # 살아 있는 애들만 벡터로 # 원본 metrix형태 없음. True로 필터된 애들만 vector로 나옴
print(arr_2d[arr_2d < 6])

# 조건에 맞는 행만 선택
row_mask = np.array([True, False, True ])
print(arr_2d)
print(arr_2d[row_mask]) # row T,F,T -> 0.2 row만 뽑음



# 그게 왜 될꺼라고 생각하세요? ㅋㅋ 






[6 7 8 9]
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


In [ ]:
# Fancy 인덱싱

arr = np.arange(10, 60, 10)
print(arr)

# arr[1,2] -> arr[1],[2]

arr[[1,2]] # -> arr[1], arr[2]를 뽑아라
arr[[0,2,3]] # -> arr[0], arr[2], arr[3]만 가져와라
 
print(arr[[0,0,1,1,2]]) # 대괄호 안에 
print(arr[[4,2,3,1,0]]) # 대괄호 안에 또 대괄화가 나오면 그 때 Fancy 인덱싱입니다.

[10 20 30 40 50]
[10 10 20 20 30]


In [ ]:
# 다차원 Fancy 인덱싱

arr_2d = np.arange(1,10).reshape(3,3)
print(arr_2d)

print(arr_2d[0]) # row 0

# 특정 행만 선택
print(arr_2d[[0,2]]) # row0,2

print()

# 행과 열을 동시에 선택
print(
    arr_2d[ # (0,0),(1,2),(2,1) 순서로 벡터 만듦
        [0,1,2],
        [2,2,1]
    ]
)

# 행렬의 특정 열을 순서 바꾸기
print(
    arr_2d[
        :, # 모든 행
        [2,0,1] # 열 idx릉 이렇게 바꿔라
    ]
)

# 행렬의 특정 

In [ ]:
# 실습 

 10부터 20까지의 정수 배열 생성
arr = np.arange(10, 21)
print('원본', arr)

# 문제1: 배열의 첫 번째, 세 번째, 마지막 요소 출력

# 문제2: 인덱스 2부터 5까지 요소 출력

# 문제3: 처음부터 5번째 요소까지 모든 짝수 인덱스 요소 출력

# 문제4: 배열의 요소를 역순으로 출력

In [ ]:
# 3 * 4 matrix
matrix = np.arange(12).reshape(3, 4)
print('원본', matrix)

# 문제1: (1,2) 위치의 요소 출력

print(matrix[1,2])

# 문제2: 두 번째 행 전체 출력
matrix[1]

# 문제3: 마지막 열 전체 출력
matrix[:,-1]

# 문제4: 첫 번째와 세 번째 행의 두 번째와 네 번째 열 요소만 추출

matrix[[0.2]]

원본 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6


array([ 3,  7, 11])

In [79]:
arr = np.arange(1, 21)
print('원본', arr)

# 문제1: 5의 배수만 선택하여 출력

arr(arr[arr % 5 ==0])

# 문제2: 3보다 크고 15보다 작은 요소 선택

# 문제3: 7의 배수이거나 홀수인 요소 선택

원본 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
matrix = np.arange(1, 21).reshape(5, 4)
print('원본', matrix)

# 문제4: 10보다 큰 요소만 100으로 변경 (슬라이싱/불리언인덱싱 -> 뷰 생성(원본 데이터 연결))

print(matrix[matrix>10])

matrix[matrix>10] = 100

print(matrix)



원본 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[11 12 13 14 15 16 17 18 19 20]


In [84]:
선형대수 연산

SyntaxError: invalid syntax (1149509561.py, line 1)

## 선형대수 연산

### 


In [85]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a ** 2)
print(a ** b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[ 1  4  9 16]
[    1    64  2187 65536]


In [86]:
a = np.array([True, False, True, False])
b = np.array([False, True, True, False])

# 논리연산
# AND
print(a & b)
# OR
print(a | b)
# NOT
print(~a)

[False False  True False]
[ True  True  True False]
[False  True False  True]


### 벡터(1줄) <-> 스칼라(단일값) 연산
> Broadcasting (스칼라가 배열 크기에 맞게 확장)



In [ ]:
# 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 스칼라 덧셈
print(arr + 10)     # [11 12 13 14 15]

# 스칼라 뺄셈
print(arr - 1)      # [0 1 2 3 4]

# 스칼라 곱셈
print(arr * 2)      # [2 4 6 8 10]

# 스칼라 나눗셈
print(arr / 2)      # [0.5 1.  1.5 2.  2.5]

# 스칼라 거듭제곱
print(arr ** 2)     # [ 1  4  9 16 25]

# 스칼라 비교 (불리언 배열)
print(arr > 3)      # [False False False  True  True]
print(arr == 2)     # [False  True False False False]



[11 12 13 14 15]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[False False False  True  True]
[False  True False False False]


### 매트릭스(2D) <-> 스칼라(단일값) 연산

In [ ]:
# 2차원 배열
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 스칼라 연산 
print(arr_2d + 10)
# [[11 12 13]
#  [14 15 16]]

print(arr_2d * 3)
# [[ 3  6  9]
#  [12 15 18]]


# 얘도 브로드 캐스트다

[[11 12 13]
 [14 15 16]]
[[ 3  6  9]
 [12 15 18]]


### 매트릭스(행렬) <-> 벡터(1줄) 연산

In [89]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

# 행렬 + 행 벡터
print(matrix + vector)

# 열 벡터 브로드캐스팅
col_vec = np.array(
    [
        [100],
        [200]
    ]
)
print(matrix + col_vec)

[[11 22 33]
 [14 25 36]]
[[101 102 103]
 [204 205 206]]


In [91]:

# 브로드 캐스팅 가능한 경우

A = np.ones((3, 2))       # 3x2 배열
B = np.ones((2,))         # 길이 2인 1차원 배열 (1x2로 해석) (행벡터)
C = np.ones((3, 1))       # 3x1 배열 (사실상 열벡터)

print("A + B 형태:", (A + B).shape)  # (3, 2) - B는 각 행에 브로드캐스팅
print(A + B)


print("A + C 형태:", (A + C).shape)  # (3, 2) - C는 각 열에 브로드캐스팅
print(A + C)

A + B 형태: (3, 2)
[[2. 2.]
 [2. 2.]
 [2. 2.]]
A + C 형태: (3, 2)
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [94]:
# 뷰(원본 데이터와 링크) 와 복사본(완전 별도) 차이, 파이썬은 슬라이싱에서 뷰가 없이 복사본만 

arr = np.arange(1,6)
print(arr)

# 슬라이싱 -> 뷰 생성
view = arr[1:4]
print(view)

view[0] = 20
print(arr)

# 복사본..?
copy = arr.copy()
copy[0] = 100
print(arr,copy)  

[1 2 3 4 5]
[2 3 4]
[ 1 20  3  4  5]
[ 1 20  3  4  5] [100  20   3   4   5]


In [95]:
# 연산 중

In [99]:
arr1 = np.array([8,12,6,10])
arr2 = np.array([3,4,1,20])

print(arr1**2)
print(arr1**0.5, np.sqrt(arr1)) #루트와 같은 결과
# 각 자리 마다 최대닶만 모음
print(np.maximum(arr1, arr2))
# arr1 과 arr2의 모든 자리수를 더한 총합
print(np.sum(arr1+arr2))

[ 64 144  36 100]
[2.82842712 3.46410162 2.44948974 3.16227766] [2.82842712 3.46410162 2.44948974 3.16227766]
[ 8 12  6 20]
64


In [100]:
# 테스트 배열
x = np.array([0, np.pi/4, np.pi/2, np.pi])
y = np.array([1, 2, 3, 4])

# 삼각함수
print("sin(x) =", np.sin(x))  # [0., 0.70710678, 1., 0.]
print("cos(x) =", np.cos(x))  # [1., 0.70710678, 0., -1.]
print("tan(x) =", np.tan(x))  # [0., 1., 16331239353195370., 0.]

# 역삼각함수
print("arcsin(sin(x)) =", np.arcsin(np.sin(x)))

# 지수와 로그
print("exp(y) =", np.exp(y))  # [2.71828183, 7.3890561, 20.08553692, 54.59815003]
print("log(y) =", np.log(y))  # [0., 0.69314718, 1.09861229, 1.38629436]
print("log10(y) =", np.log10(y))  # [0., 0.30103, 0.47712125, 0.60205999]
print("log2(y) =", np.log2(y))  # [0., 1., 1.58496250, 2.]

# 제곱근과 거듭제곱
print("sqrt(y) =", np.sqrt(y))  # [1., 1.41421356, 1.73205081, 2.]
print("power(y, 2) =", np.power(y, 2))  # [1, 4, 9, 16]

# 절대값과 부호
z = np.array([-2, -1, 0, 1, 2])
print("abs(z) =", np.abs(z))  # [2 1 0 1 2]
print("sign(z) =", np.sign(z))  # [-1 -1  0  1  1]

# 소수점 처리
w = np.array([1.2, 2.7, 3.5, 4.9])
print("floor(w) =", np.floor(w))  # [1. 2. 3. 4.] (내림)
print("ceil(w) =", np.ceil(w))   # [2. 3. 4. 5.] (올림)
print("round(w) =", np.round(w))  # [1. 3. 4. 5.] (반올림)
print("trunc(w) =", np.trunc(w))  # [1. 2. 3. 4.] (소수점 버림)

sin(x) = [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos(x) = [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
tan(x) = [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(sin(x)) = [0.00000000e+00 7.85398163e-01 1.57079633e+00 1.22464680e-16]
exp(y) = [ 2.71828183  7.3890561  20.08553692 54.59815003]
log(y) = [0.         0.69314718 1.09861229 1.38629436]
log10(y) = [0.         0.30103    0.47712125 0.60205999]
log2(y) = [0.        1.        1.5849625 2.       ]
sqrt(y) = [1.         1.41421356 1.73205081 2.        ]
power(y, 2) = [ 1  4  9 16]
abs(z) = [2 1 0 1 2]
sign(z) = [-1 -1  0  1  1]
floor(w) = [1. 2. 3. 4.]
ceil(w) = [2. 3. 4. 5.]
round(w) = [1. 3. 4. 5.]
trunc(w) = [1. 2. 3. 4.]


In [102]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 기본 집계
print("합계:", np.sum(arr))          # 45
print("평균:", np.mean(arr))         # 5.0
print("최소값:", np.min(arr))        # 1
print("최대값:", np.max(arr))        # 9
print("표준편차:", np.std(arr))      # 2.581988897471611
print("분산:", np.var(arr))          # 6.666666666666667

합계: 45
평균: 5.0
최소값: 1
최대값: 9
표준편차: 2.581988897471611
분산: 6.666666666666667


In [103]:
# 축을 따라 집계
print("행별 합계:", np.sum(arr, axis=1))  # [ 6 15 24]
print("열별 합계:", np.sum(arr, axis=0))  # [12 15 18]
print("행별 평균:", np.mean(arr, axis=1))  # [2. 5. 8.]
print("열별 평균:", np.mean(arr, axis=0))  # [4. 5. 6.]
print("행별 최소값:", np.min(arr, axis=1))  # [1 4 7]
print("열별 최소값:", np.min(arr, axis=0))  # [1 2 3]

행별 합계: [ 6 15 24]
열별 합계: [12 15 18]
행별 평균: [2. 5. 8.]
열별 평균: [4. 5. 6.]
행별 최소값: [1 4 7]
열별 최소값: [1 2 3]


In [106]:
# 누적 합계 (cumulative sum)
print(arr)
print("누적 합계:", np.cumsum(arr))  # [ 1  3  6 10 15 21 28 36 45]
print("행별 누적 합계:")
print(np.cumsum(arr, axis=1))
# [[ 1  3  6]
#  [ 4  9 15]
#  [ 7 15 24]]

# 누적 곱 (cumulative product)
print("누적 곱:", np.cumprod(arr))  # [1 2 6 24 120 720 5040 40320 362880]

# 중앙값 (median)
print("중앙값:", np.median(arr))        # 5.0
print("행별 중앙값:", np.median(arr, axis=1))  # [2. 5. 8.]
print("열별 중앙값:", np.median(arr, axis=0))  # [4. 5. 6.]

# 백분위수 (percentile)
print("25% 백분위수:", np.percentile(arr, 25))  # 3.0
print("50% 백분위수:", np.percentile(arr, 50))  # 5.0 (중앙값과 동일)
print("75% 백분위수:", np.percentile(arr, 75))  # 7.0

# 가중 평균 (weighted average)
weights = np.array([0.1, 0.3, 0.6])  # 가중치
data = np.array([2, 5, 8])
print("가중 평균:", np.average(data, weights=weights))  # 6.1

[[1 2 3]
 [4 5 6]
 [7 8 9]]
누적 합계: [ 1  3  6 10 15 21 28 36 45]
행별 누적 합계:
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
누적 곱: [     1      2      6     24    120    720   5040  40320 362880]
중앙값: 5.0
행별 중앙값: [2. 5. 8.]
열별 중앙값: [4. 5. 6.]
25% 백분위수: 3.0
50% 백분위수: 5.0
75% 백분위수: 7.0
가중 평균: 6.5


In [107]:
# 샘플 배열
arr = np.arange(12)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 균등 분할
print("3개로 균등 분할:")
print(np.split(arr, 3))  # [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 위치 지정 분할
print("위치 지정 분할 (인덱스 3, 8 기준):")
print(np.split(arr, [3, 8]))  # [array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]

# 2차원 배열 분할
arr_2d = np.arange(16).reshape(4, 4)
print("2차원 배열:")
print(arr_2d)

# 행 방향 분할
print("행 방향 분할:")
print(np.split(arr_2d, 2, axis=0))  # 2개 배열로 (각 2x4)
print(np.vsplit(arr_2d, 2))  # 동일한 결과

# 열 방향 분할
print("열 방향 분할:")
print(np.split(arr_2d, 2, axis=1))  # 2개 배열로 (각 4x2)
print(np.hsplit(arr_2d, 2))  # 동일한 결과

3개로 균등 분할:
[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
위치 지정 분할 (인덱스 3, 8 기준):
[array([0, 1, 2]), array([3, 4, 5, 6, 7]), array([ 8,  9, 10, 11])]
2차원 배열:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
행 방향 분할:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
열 방향 분할:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [1]:
# 학급별 시험 점수 (5개 학급, 각 10명의 학생)
scores = np.random.randint(50, 101, size=(5, 10))  # 50~100 사이 점수
print("학급별 점수:")
print(scores)

# 문제1: 전체 평균과 표준편차

# 문제2: 학급별 최고점과 최저점

# 문제3: 전체 학생 중 상위 25%와 하위 25% 컷오프 점수

# 문제4: 학급별 평균이 가장 높은/낮은 학급 찾기

NameError: name 'np' is not defined

In [ ]:
# %pip install tensorflow






Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [88]:
import numpy as np

In [90]:
# ???

# 1차원 배열 결합
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concat((arr1,arr2)) #concaten : 이어 붙이다는 영단어


# 2차원 배열 결합

arr2d1 = np.array([[1,2],[3,4]])
arr2d2 = np.array([[5,6],[7,8]])




AttributeError: module 'numpy' has no attribute 'concat'

# [강사님 자료](https://github.com/verba-neo/gaida-1/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D/01_numpy.ipynb)

In [91]:

# 1차원 배열 결합
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concat( (arr1, arr2) )  # np.concatenate 도 같음
print(result)

# 2차원 배열 결합
arr2d1 = np.array([ [1, 2], [3, 4] ])
arr2d2 = np.array([ [5, 6], [7, 8] ])

# concat, axis=0 == vstack
result2 = np.concat( (arr2d1, arr2d2), axis=0)
result22 = np.vstack( (arr2d1, arr2d2) )
print(result2)
print(result22)
# concat, axis=1 == hstack
result3 = np.concat( (arr2d1, arr2d2), axis=1)
result33 = np.hstack( (arr2d1, arr2d2) )
print(result3)

# matrix 두개를 겹친다 => Tensor
result4 = np.dstack( (arr2d1, arr2d2) )
print(result4)

AttributeError: module 'numpy' has no attribute 'concat'

In [ ]:
# 차원 축소 | squeeze



arr = np.array([[1],[2],[3]])
print(arr,arr.shape)

# 모든 단일 차원 (shape에서 1 나온 것들 제거)
print(np.squeeze(arr))

# 특정 축만 제거
arr2 = np.array([[[1,2,3]]])
print(arr2,arr2.shape) #113 

arr_3d = arr2

print(np.squeeze(arr2, axis=1)) #13
#----
arr_2d = np.squeeze(arr2, axis=1)

print(arr_2d)






[[1]
 [2]
 [3]] (3, 1)
[1 2 3]
[[[1 2 3]]] (1, 1, 3)
[[1 2 3]]
[[1 2 3]]


# 유틸리티 함수

In [45]:
# where 

arr = np.arange(10)

print(arr)

# 벡터 예시
# 단순 필터링 : 짝수 예시 
print(np.where(arr %2==0)
      )

print(np.where(arr%2==0,'짝수','홀수'))

# 메트릭스 예시
# 0~10까지 랜덤으로 3x3
arr2d = np.random.randint(0,10,(3,3))
print(arr2d)

# 조건만 걸면, 좌표가 나옴
np.where(arr2d>5) 

# 5보다 큰 값들은 *2, 아니면 그대로
print(np.where(arr2d > 5, arr2d *2, arr2d))

# 좌표값 사용하는건가???

# 그냥 고건에 맞는 값들만 보고 싶으면 




[0 1 2 3 4 5 6 7 8 9]
(array([0, 2, 4, 6, 8]),)
['짝수' '홀수' '짝수' '홀수' '짝수' '홀수' '짝수' '홀수' '짝수' '홀수']
[[3 7 8]
 [3 6 9]
 [7 7 9]]
[[ 3 14 16]
 [ 3 12 18]
 [14 14 18]]


In [ ]:
# argmax, argmin

# 벡터에서 최대/최소 위치
arr = np.array([3,5,1,0,4])

max_idx = np.argmax(arr)
min_idx = np.argmin(arr)

print(max_idx,min_idx)

# 매트릭스에서 최대/최소

np.random.seed(24) # seed는 고정이야
arr2d = np.random.randint(0,10,(3,3))
print(arr2d)

row_max = np.argmax(arr2d,axis=1)

print(row_max)

col_min = np.argmin(arr2d,axis=0)
print(col_min)




1 3
[[2 3 0]
 [7 1 1]
 [1 4 4]]
[1 0 1]
[2 1 0]


In [23]:
# unique 고유값 찾기
from enum import unique


arr = np.array([1,2,3,2,3,4,3,4,1,3,2])

unique_values = np.unique(arr)
print(unique_values)

np.unique(arr, return_counts=True)

# 값들만
unique_values = np.unique(arr)
print(unique_values)

# 값들 , 개수
values, count =np.unique(arr, return_counts=True)

print(values)
print(count)

# 값들, 개수 -> dict
freq_dict = dict(zip(values,count))
print(freq_dict)

# 가장 많이 등장하는 숫자 찾기


[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[2 3 4 2]
{1: 2, 2: 3, 3: 4, 4: 2}


In [28]:
# sort, argsort

arr = np.array([3,5,1,0,4])

# 오름차순 정렬 ASC
print(np.sort(arr))

# 내림차순 정렬 DESC
print(np.sort(arr)[::-1]) # 뒤집어주는 flip기능도 있긴한데 굳이 쓸 필요는?


# 정렬 후, 원래 인덱스를 반환
np.argsort(arr) 

# 정렬하기 위한 인덱스 배치

idx = np.argsort(arr) 
print(idx)

print(arr[idx])





[0 1 3 4 5]
[5 4 3 1 0]
[3 2 0 4 1]
[0 1 3 4 5]


# Matrix 정렬

In [32]:
# Matrix 정렬
arr2d = np.random.randint(0, 10, (3,4))
print(arr2d)


# 행별 정렬
row_sorted =np.sort(arr2d, axis=1)
print(row_sorted)


# 열별 정렬
col_sorted =np.sort(arr2d, axis=0)[::-1]
print(col_sorted)


[[0 5 2 4]
 [6 0 8 6]
 [2 5 7 4]]
[[0 2 4 5]
 [0 6 6 8]
 [2 4 5 7]]
[[6 5 8 6]
 [2 5 7 4]
 [0 0 2 4]]


In [37]:
# 가상의 학생 시험 점수 데이터
math_scores = np.array([85, 90, 75, 95, 70, 80, 65, 75, 90, 85])
science_scores = np.array([90, 85, 80, 95, 70, 75, 65, 80, 85, 90])
english_scores = np.array([80, 85, 90, 80, 75, 90, 70, 75, 85, 95])

subjects = ['수학', '과학', '영어']
scores = np.vstack((math_scores, science_scores, english_scores))

print(scores)

print(np.array(scores))




[[85 90 75 95 70 80 65 75 90 85]
 [90 85 80 95 70 75 65 80 85 90]
 [80 85 90 80 75 90 70 75 85 95]]
[[85 90 75 95 70 80 65 75 90 85]
 [90 85 80 95 70 75 65 80 85 90]
 [80 85 90 80 75 90 70 75 85 95]]


In [ ]:
# 기본 통계 (과목별 평균, 중앙값, *표준편차*, 최소, 최대)
subject_avg = np.mean(scores, axis=1)

print(subject_avg)
print(np.median(scores,axis=1))
print(np.std(scores,axis=1))
print(np.min(scores,axis=1))
print(np.max(scores,axis=1))






[81.  81.5 82.5]
[82.5 82.5 82.5]
[9.16515139 8.95823643 7.5       ]
[65 65 70]
[95 95 95]


In [58]:
# 총점 기준 상위 3명 학생의 정보 표시
# | 학생번호(idx) | 수학 | 과학 | 영어 | 총점 |


## 총점 기준 : 수학, 과학, 영어의 총합
total_scores = np.sum(scores,axis=0)
print(total_scores)

desc_scores = np.argsort(total_scores)[:: -1]  # [::-1] DESC라고 위쪽에 나와 있음
print(desc_scores)

print(np.argsort(total_scores)[-3:])

ranker3_scores = np.argsort(desc_scores)[-3:]
print(ranker3_scores)




### 행렬을 뷰 단위로 (위, 아래로 합쳐서 메트릭스를 벡터화하고 거기서 가장 큰 값 3위까지 탐색해서 좌표를 추출하면 된다.)
### 그 다음 좌표를 인덱스로 각각의 행에서 뽑으면 되는 것이고 




[255 260 245 270 215 245 200 230 260 270]
[9 3 8 1 0 5 2 7 4 6]
[8 3 9]
[7 2 0]


In [ ]:
# 기본 통계 (과목별 평균, 중앙값, *표준편차*, 최소, 최대)

from numpy import median


for idx, subject in enumerate(scores): # 'enumerate' 나 이거 몰라 / 인덱스와 값을 동시에 반복할 수 있게 해주는 함수
    mean_score = np.mean(subject)
    # 평균 mean
    mean_score = np.mean(subject)
    # 중앙값 median
    median_score = np.median(subject)
    # 표준편차 standard
    std_dev = np.std(subject)
    # 최소 min
    min_score = np.min(subject)
    # 최소 max 
    max_score = np.max(subject)



    # print에서 \ 역슬래쉬하면 줄띄기 됨


In [66]:
# 총점 기준 상위 3명 학생의 정보 표시
# | 학생번호(idx) | 수학 | 과학 | 영어 | 총점 |

# 과목 총점 배열
total_scores = np.sum(scores,axis=0)

print(total_scores)

# 총점 desc 정렬 후 3명 잘라서 idx만 내놔
top_students = np.argsort(total_scores) [::-1][:3]

print('학생 번호 | 수학 | 과학 | 영어 | 총점 ')
for idx in top_students:
    print(
        f'{idx+1:^7} |{math_scores[idx]:^3} | {science_scores[idx]:^4} |' # ^7 7칸 정렬
        f'{english_scores[idx]:^3}|{total_scores[idx]}'
    )



[255 260 245 270 215 245 200 230 260 270]
학생 번호 | 수학 | 과학 | 영어 | 총점 
  10    |85  |  90  |95 |270
   4    |95  |  95  |80 |270
   9    |90  |  85  |85 |260


In [67]:
# 과목별 상관관계

correlation = np.corrcoef(scores)
print("과목 간 상관관계:")
for i in range(3):
    for j in range(i+1, 3):
        print(f"{subjects[i]}-{subjects[j]} 상관계수: {correlation[i, j]:.4f}")

과목 간 상관관계:
수학-과학 상관계수: 0.8952
수학-영어 상관계수: 0.4728
과학-영어 상관계수: 0.4651
